### PR TITLE
Added dwriteRectScale(...)

### PR DESCRIPTION
**Pull request by newdigate**
Found this method to be quite useful... :P

### CODE REVIEW

**Comment by FrankBoesing** [comment]
Can't try it at the moment, but looks very interesting!

**Comment by FrankBoesing** [comment]
thanks

**Comment by newdigate** [comment]
here is an example of how Im using the function: https://github.com/newdigate/teensy_audio_tft/tree/master/Teensy3.6/ILI9431_SDWave_DMA 
:)

**Comment by FrankBoesing** [comment]
Hm, looks interesting, but it does not work..
Something is wrong with the Sketch. It displays a small rect with stripes, and there is no sound.

**Comment by newdigate** [comment]
Oh, forgot to mention: The sketch needs an SD card inserted into the Teensy 3.6 with the wave and bmp files on the SD card.... It may also need to be built with latest Arduino and Teensyduino beta.... 
I'll attach a better example with no dependencies when I get a chance... :)

**Pull request merged**
